[versions]
# sdk
compileSdk = "33"
targetSdk = "33"
minSdk = "24"
jvmTarget = "1.8"

# plugin
hilt-plugin = "2.42"

# library
android-gradle = "7.4.1"
compose = "1.3.3"
core-ktx = "1.9.0"
fragment-ktx = "1.5.5"
appcompat = "1.5.1"
material = "1.6.1"
compose-material3 = "1.0.0-beta02"
lifecycle-runtime = "2.5.1"
activity-compose = "1.5.1"
junit = "4.13.2"
junit-test = "1.1.3"
test-ext-junit = "1.1.3"
espresso-core = "3.4.0"
compose-compiler = "1.4.3"
hilt = "2.44"
kotlin = "1.8.0"
kotlin-kapt = "1.8.10"
coil-compose = "2.2.1"
compose-navigation = "2.5.2"
compose-hilt-navigation = "1.0.0"
retrofit = "2.9.0"
kotlinx-serialization-json = "1.4.0"
kotlinx-serialization-converter = "0.8.0"
okhttp = "5.0.0-alpha.10"
test-core = "1.4.0"
androidx-lifecycle-viewmodel-ktx = "2.5.1"
accompanist-pager = "0.26.5-rc"
accompanist-swipe-refresh = "0.26.5-rc"
androidx-navigation = "2.5.3"

[libraries]
# andoridx
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx"}
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel-ktx" }
androidx-navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation"}
# androidx-compose
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose-material3" }
androidx-compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

# androidx-navigation-compose
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
androidx-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "compose-hilt-navigation" }

# andoidx-test
androidx-test-core = { module = "androidx.test:core", version.ref = "test-core"}
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "test-core"}
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "junit-test" }
androidx-test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit-test" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }

# hilt
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt-plugin" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

# junit
junit = { module = "junit:junit", version.ref = "junit" }

# retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

# kotlin-serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-converter" }

# okhttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

# coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }

# kotlin plugin
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# google-accompanist
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-pager"}
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist-pager"}
accompanist-swipe-refresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist-swipe-refresh"}

[bundles]
androidx-compose = ["androidx-compose-ui", "androidx-compose-ui-tooling", "androidx-compose-ui-tooling-preview", "androidx-activity-compose"]
androidx-compose-test = ["androidx-compose-test-junit4", "androidx-compose-ui-test-manifest"]
androidx-navigation-compose = ["androidx-navigation-compose", "androidx-hilt-navigation"]
androidx-test = ["androidx-test-core", "androidx-test-core", "androidx-test-junit", "androidx-test-junit-ktx"]
kotlinx-serialization = ["kotlinx-serialization-json", "kotlinx-serialization-converter"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-kapt" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }